Windows build support
MSc-21-22/TaintAnalysisCpu pull request #38
Opened 2022-02-11 10:45 UTC by thorulf4

2022-02-11 12:33 UTC, NicklasHugoy commented on .vscode/settings.json
> +        "climits": "cpp"
😭

2022-02-11 13:02 UTC, NicklasHugoy requested changes

2022-02-11 13:02 UTC, NicklasHugoy commented on src/matrix_analysis.cu
> +    test_watch.print_time<Microseconds>("test timer ");
This doesn't time anything?

2022-02-14 08:25 UTC, NicklasHugoy approved these changes

2022-02-14 08:33 UTC, ZcortezZ approved these changes

2022-02-14 08:34 UTC, merged