Added cuda draft implementation
MSc-21-22/TaintAnalysisCpu pull request #39
Opened 2022-02-14 10:34 UTC by thorulf4

2022-02-15 12:46 UTC, NicklasHugoy commented on src/bit_cuda/analysis.cu
> +
Why are we doing this twice?

2022-02-16 10:44 UTC, NicklasHugoy requested changes

2022-02-16 10:44 UTC, NicklasHugoy commented on src/bit_cuda/analysis.cu
> +std::cout << "Test1\n";
Remove?

2022-02-16 10:44 UTC, NicklasHugoy commented on src/bit_cuda/bit_cuda_transformer.h
> +#define TAINT_VAR "$"
Already included from cfg.h

2022-02-16 10:44 UTC, NicklasHugoy commented on src/bit_cuda/bit_cuda_transformer.h
> +        std::cout << RETURN_VAR << " -> " << variables[RETURN_VAR] << " : " << (1 << variables[RETURN_VAR])  <<'\n';
Delete test prints

2022-02-16 10:44 UTC, NicklasHugoy commented on src/bit_cuda/bit_cuda_transformer.h
> +                std::cout << *it << " -> " << variables[*it] << " : " << (1 << variables[*it])  <<'\n';
Delete test prints

2022-02-17 08:58 UTC, NicklasHugoy commented on src/bit_cuda/bit_cuda_transformer.h
> +            fill_with_variable_indices(node_struct.transfer.rhs, node.arguments[0]);
`node_struct.transfer.x` is never assigned to anything

2022-02-17 09:03 UTC, NicklasHugoy commented on src/main.cpp
> +                bit_cuda::execute_analysis, &transformer.nodes[0], transformer.nodes.size(), &*transformer.extra_transfers.begin(), transformer.extra_transfers.size());
Use `&transformer.extra_transfers[0]` instead?

2022-02-18 09:48 UTC, ZcortezZ approved these changes

2022-02-18 09:49 UTC, merged