Cuda worklist implementation
MSc-21-22/TaintAnalysisCpu pull request #47
Opened 2022-02-24 08:39 UTC by NicklasHugoy

2022-03-04 12:19 UTC, ZcortezZ submitted a review, later dismissed

2022-03-07 08:16 UTC, thorulf4 requested changes

2022-03-07 08:16 UTC, thorulf4 commented on src/cuda/cuda_common.cu
> +void cuda_allocate_memory(void **devPtr, size_t size){
Returning a device pointer instead would make this code nicer to use

2022-03-07 08:46 UTC, thorulf4 approved these changes

2022-03-07 08:53 UTC, ZcortezZ approved these changes

2022-03-07 09:00 UTC, merged