Benchmark all and compare
MSc-21-22/TaintAnalysisCpu pull request #58
Opened 2022-03-11 08:38 UTC by NicklasHugoy

2022-03-14 12:49 UTC, thorulf4 requested changes
Tiny change but other than that it seems good.

2022-03-14 12:49 UTC, thorulf4 commented on src/main.cpp
> +            init_gpu();
init_gpu should probably be called before cublas, to ensure fairness even if we dont quite know if it has an impact.

2022-03-21 10:19 UTC, thorulf4 approved these changes

2022-03-21 10:25 UTC, thorulf4 approved these changes
😢


edit:
Make CI run benchmarks for each commit haha

2022-03-21 10:26 UTC, ZcortezZ approved these changes

2022-03-21 10:51 UTC, merged