Cpu optimization for single colored taint analysis
MSc-21-22/TaintAnalysisCpu pull request #66
Opened 2022-04-04 10:47 UTC by thorulf4

2022-04-04 11:16 UTC, ZcortezZ submitted a review, later dismissed

2022-04-04 11:27 UTC, NicklasHugoy requested changes
Could be nice with more code-reuse, so we reuse the structs and pre-analysis components for both the CPU and GPU analysis. This would also make it easier to show that we're roughly doing analysis the same way for GPU and CPU

2022-04-04 11:27 UTC, NicklasHugoy commented on src/cfg/transformations/analysis_converter.cpp
> +#include <iostream>
Why is include here? and is it even used in this code?

2022-04-05 12:00 UTC, ZcortezZ approved these changes

2022-04-06 08:14 UTC, NicklasHugoy requested changes

2022-04-06 08:14 UTC, NicklasHugoy commented on src/cuda/cuda_transformer.h
>      }
function signature has been changed so maybe `get_variable_indices` is a better name now?

2022-04-06 08:27 UTC, NicklasHugoy approved these changes

2022-04-06 08:28 UTC, ZcortezZ approved these changes

2022-04-06 08:34 UTC, merged